INSERT INTO public.companies (id, name, industry, location)
VALUES
  ('smarthr',            'SmartHR',                    'HRテック',                '東京都港区'),
  ('dena',               'DeNA',                       'ゲーム・エンターテインメント','東京都渋谷区'),
  ('gree',               'GREE',                       'ゲーム・SNS',             '東京都港区'),
  ('gunosy',             'Gunosy',                     'メディア・情報配信',       '東京都港区'),
  ('chatwork',           'Chatwork',                   'SaaS・コミュニケーション', '東京都港区'),
  ('visional',           'Visional（BizReach）',        'HRテック・転職',           '東京都渋谷区'),
  ('sansan',             'Sansan',                     'SaaS・名刺管理',          '東京都渋谷区'),
  ('uzabase',            'Uzabase（NewsPicks）',        'メディア・経済情報',       '東京都港区'),
  ('base',               'BASE',                       'Eコマース・フィンテック',  '東京都港区'),
  ('zozo',               'ZOZO',                       'Eコマース・ファッション',  '千葉県千葉市'),
  ('layerx',             'LayerX',                     'フィンテック・SaaS',       '東京都中央区'),
  ('findy',              'Findy',                      'HRテック・エンジニア転職', '東京都品川区'),
  ('crowdworks',         'CrowdWorks',                 'クラウドソーシング',       '東京都渋谷区'),
  ('coconala',           'coconala',                   'スキルマーケット',         '東京都渋谷区'),
  ('ubie',               'Ubie',                       'ヘルステック',             '東京都中央区'),
  ('timee',              'Timee',                      'HRテック・スポットワーク', '東京都新宿区'),
  ('recruit',            'リクルート',                 'HR・情報サービス',         '東京都千代田区'),
  ('nttdata',            'NTTデータ',                  'SIer・ITサービス',         '東京都江東区'),
  ('dwango',             'ドワンゴ',                   'エンターテインメント・動画','東京都中央区'),
  ('monotaro',           'MonotaRO',                   'Eコマース・BtoB',          '大阪府吹田市'),
  ('retty',              'Retty',                      'グルメ・メディア',         '東京都港区'),
  ('classi',             'Classi',                     'EdTech',                  '東京都新宿区'),
  ('smartnews',          'SmartNews',                  'メディア・ニュースアプリ', '東京都渋谷区'),
  ('speee',              'Speee',                      'デジタルマーケティング',   '東京都港区'),
  ('eureka',             'Eureka（Pairs）',             'マッチングサービス',       '東京都港区'),
  ('preferred-networks', 'Preferred Networks',         'AI・機械学習',             '東京都千代田区'),
  ('plaid',              'Plaid',                      'CX・SaaS',                '東京都中央区'),
  ('appier',             'Appier',                     'AI・マーケティング',       '東京都渋谷区'),
  ('treasure-data',      'Treasure Data',              'データマネジメント・CDP',  '東京都千代田区'),
  ('hamee',              'Hamee',                      'Eコマース支援・SaaS',      '神奈川県小田原市'),
  ('yappli',             'Yappli',                     'ノーコード・SaaS',         '東京都港区'),
  ('gmo-pg',             'GMOペイメントゲートウェイ',  'フィンテック・決済',       '東京都渋谷区'),
  ('fujitsu',            '富士通',                     'SIer・ITサービス',         '東京都港区'),
  ('nec',                'NEC',                        'SIer・ITサービス',         '東京都港区'),
  ('tis',                'TIS',                        'SIer・ITサービス',         '東京都新宿区'),
  ('scsk',               'SCSK',                       'SIer・ITサービス',         '東京都江東区'),
  ('aucfan',             'オークファン',               'Eコマース・価格比較',      '東京都千代田区'),
  ('kaizen-platform',    'Kaizen Platform',            'デジタルマーケティング',   '東京都新宿区'),
  ('medpeer',            'MedPeer',                    'ヘルステック・医師向けSaaS','東京都渋谷区'),
  ('caddi',              'CADDi',                      '製造業DX・調達SaaS',       '東京都千代田区')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.company_scores (company_id, tech_stack_modernity, remote_rate, estimated_overtime_hours, turnover_rate, retention_rate, dev_environment, skill_up_support)
VALUES
  ('smarthr',            5, 50, 30, 15, 80, 5, 5),
  ('dena',               5, 50, 30, 15, 80, 5, 5),
  ('gree',               5, 50, 30, 15, 80, 5, 5),
  ('gunosy',             5, 50, 30, 15, 80, 5, 5),
  ('chatwork',           5, 50, 30, 15, 80, 5, 5),
  ('visional',           5, 50, 30, 15, 80, 5, 5),
  ('sansan',             5, 50, 30, 15, 80, 5, 5),
  ('uzabase',            5, 50, 30, 15, 80, 5, 5),
  ('base',               5, 50, 30, 15, 80, 5, 5),
  ('zozo',               5, 50, 30, 15, 80, 5, 5),
  ('layerx',             5, 50, 30, 15, 80, 5, 5),
  ('findy',              5, 50, 30, 15, 80, 5, 5),
  ('crowdworks',         5, 50, 30, 15, 80, 5, 5),
  ('coconala',           5, 50, 30, 15, 80, 5, 5),
  ('ubie',               5, 50, 30, 15, 80, 5, 5),
  ('timee',              5, 50, 30, 15, 80, 5, 5),
  ('recruit',            5, 50, 30, 15, 80, 5, 5),
  ('nttdata',            5, 50, 30, 15, 80, 5, 5),
  ('dwango',             5, 50, 30, 15, 80, 5, 5),
  ('monotaro',           5, 50, 30, 15, 80, 5, 5),
  ('retty',              5, 50, 30, 15, 80, 5, 5),
  ('classi',             5, 50, 30, 15, 80, 5, 5),
  ('smartnews',          5, 50, 30, 15, 80, 5, 5),
  ('speee',              5, 50, 30, 15, 80, 5, 5),
  ('eureka',             5, 50, 30, 15, 80, 5, 5),
  ('preferred-networks', 5, 50, 30, 15, 80, 5, 5),
  ('plaid',              5, 50, 30, 15, 80, 5, 5),
  ('appier',             5, 50, 30, 15, 80, 5, 5),
  ('treasure-data',      5, 50, 30, 15, 80, 5, 5),
  ('hamee',              5, 50, 30, 15, 80, 5, 5),
  ('yappli',             5, 50, 30, 15, 80, 5, 5),
  ('gmo-pg',             5, 50, 30, 15, 80, 5, 5),
  ('fujitsu',            5, 50, 30, 15, 80, 5, 5),
  ('nec',                5, 50, 30, 15, 80, 5, 5),
  ('tis',                5, 50, 30, 15, 80, 5, 5),
  ('scsk',               5, 50, 30, 15, 80, 5, 5),
  ('aucfan',             5, 50, 30, 15, 80, 5, 5),
  ('kaizen-platform',    5, 50, 30, 15, 80, 5, 5),
  ('medpeer',            5, 50, 30, 15, 80, 5, 5),
  ('caddi',              5, 50, 30, 15, 80, 5, 5)
ON CONFLICT (company_id) DO NOTHING;
